### ISSUE TITLE
New Runners

### ISSUE THREAD

**Issue by CameronSewell** [cs481-ekh/f22-kitty-cat-studios#53]
- [ ] Create an interface to select a new runner
- [ ] implement a new runner
- [ ] implement at least one more runner
- [ ] new skins for the different runner
